name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build & Test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up environment
        # use the local action specified in action.yml
        uses: ./.github/workflows
      - name: Run unit tests
        run: make tests
      - name: Check memory management bugs with Valgrind
        run: make valgrind
      - name: Run CLI tests under release build
        run: chmod +x ./cli_test.sh && ./cli_test.sh -r
