name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          echo "version=${version}" >> $GITHUB_OUTPUT
      - uses: release-drafter/release-drafter@v5
        with:
          version: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
